### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-commands#5]
Hi,

How do i implement this in a voxel-engine game? Thanks!

**Comment by z3t0** [comment]
Does this work on its own or do I have to configure any other plugins for this to work?

**Comment by deathcap** [comment]
Same as in https://github.com/deathcap/voxel-console/issues/2; load with voxel-plugins

voxel-commands requires two other plugins (to do: document in readme), from the code https://github.com/deathcap/voxel-commands/blob/master/commands.coffee#L6-L14

``coffeescript

module.exports.pluginInfo =
  loadAfter: ['voxel-console']

class CommandsPlugin
  constructor: (@game, opts) ->
    @console = @game.plugins?.get 'voxel-console'
    throw new Error('voxel-commands requires voxel-console') if not @console?
    @registry = @game.plugins?.get 'voxel-registry'
    throw new Error('voxel-commands requires voxel-registry') if not @registry?
```

these can be found at https://github.com/deathcap/voxel-console and https://github.com/deathcap/voxel-registry

voxel-commands also optionally integrates with a few other plugins (also undocumented, but its in the source):

* https://github.com/deathcap/voxel-player
* https://github.com/deathcap/voxel-carry
* https://github.com/deathcap/voxel-blockdata
* https://github.com/deathcap/voxel-client

and other plugins are also able to depend on this plugin for adding their own new custom commands

**Comment by z3t0** [comment]
Thanks!
